remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin : "aqua"

baseurl: "/kuliah-season-4"

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: single
      read_time: true
      author_profile: false
      share: true
      comments: false
      sidebar:
        nav: "daftar-matkul"

locale: "id"
